Feature/sch 568: Customized skype sign-in
vora/botauth pull request #6
Opened 2018-07-30 17:36 UTC by harshvshah

2018-07-30 17:39 UTC, alexknipfer approved these changes

2018-07-30 17:44 UTC, carblue5757 requested changes

2018-07-30 17:44 UTC, carblue5757 commented on Node/src/dialogs.ts
> +                        .text(args.providerId === 'azuread-openidconnect' ? args.skypeSignIn : "connect_prompt")
I dont know that you can just call args.providerId.   Try doing what they did above for the buttonUrl -- `opt.buttonUrl`

2018-07-30 17:44 UTC, carblue5757 commented on Node/src/dialogs.ts
> +                        .text(args.providerId === 'azuread-openidconnect' ? args.skypeSignIn : "connect_prompt")
same for opt.skypeSignIn

2018-07-30 17:44 UTC, carblue5757 commented on Node/src/index.ts
> +                        else if (this.options.successRedirect) {
move the `else if` up one line, to be on the same line as the `}`

2018-07-30 17:44 UTC, carblue5757 commented on Node/src/index.ts
> +                        else {
move the else up one line.

2018-07-31 14:10 UTC, carblue5757 approved these changes

2018-07-31 14:10 UTC, merged